In [1]:
import numpy as np

In [7]:
mylist = [1, 2, 3, 4]
np.array(mylist)

array([1, 2, 3, 4])

In [8]:
np.array([range(1,10) for i in range(1, 10)])

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [9]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.zeros((2, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [15]:
np.ones([2, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.random.rand(4, 3)

array([[0.20986436, 0.0583794 , 0.17064278],
       [0.95297205, 0.92650335, 0.34639769],
       [0.67486303, 0.32783167, 0.71102233],
       [0.92947011, 0.92561753, 0.01478993]])

In [26]:
np.random.randint(1, 100, (4, 4))

array([[73, 15, 22, 75],
       [68, 24, 23, 78],
       [96, 79, 56,  7],
       [31, 13, 73, 85]])

In [27]:
np.random.randn(2, 4)

array([[ 0.93548448, -0.53944121,  0.98125562,  0.18349655],
       [-0.39250944, -0.83513467,  0.67630938, -0.20667987]])

In [32]:
np.random.random((1, 3, 4))

array([[[0.98668358, 0.6371945 , 0.9231802 , 0.81109842],
        [0.88687507, 0.26498092, 0.16165387, 0.18789138],
        [0.53624701, 0.71492987, 0.41127548, 0.13794236]]])

In [46]:
#Lineraly spaced integers
np.linspace(start=1,stop=100, num=50, endpoint=True)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [47]:
np.random.ran()

0.7500273210014504

In [50]:
np.random.seed(101)

In [57]:
np.random.randint(1, 100, (5))

array([30, 60, 35, 45, 73])

In [61]:
arr = np.random.randint(1, 100, (10,))
arr

array([53, 57, 39, 74, 53, 19, 72, 16, 45,  1])

In [65]:
arr.max()
arr.min()
arr.mean()
arr.argmax()

3

In [67]:
arr.reshape((2,))

array([[53, 57, 39, 74, 53],
       [19, 72, 16, 45,  1]])

In [90]:
mat = np.arange(0, 100).reshape((5,5, 4))
mat

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]],

       [[80, 81, 82, 83],
        [84, 85, 86, 87],
        [88, 89, 90, 91],
        [92, 93, 94, 95],
        [96, 97, 98, 99]]])

In [93]:
mat[1, 2, 3]

31

In [95]:
mat[:, :, 2]

array([[ 2,  6, 10, 14, 18],
       [22, 26, 30, 34, 38],
       [42, 46, 50, 54, 58],
       [62, 66, 70, 74, 78],
       [82, 86, 90, 94, 98]])

In [97]:
mat.reshape((10, 10))[:, 2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [101]:
#Masking
mat = mat.reshape(10, 10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [102]:
mat[mat > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [103]:
import pandas as pd

In [104]:
pd.DataFrame(mat)

0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

In [110]:
df = pd.DataFrame(np.random.randint(1, 101, (100,5)))
df.head()

0   1   2   3   4
0  35  80  27  38  12
1  94  12   9  95  15
2  51  78  11  46  86
3  86  17  20   2   8
4  61  84  90   2  45

In [119]:
df[(df > 100) | (df < 1)]

0   1   2   3   4
0  NaN NaN NaN NaN NaN
1  NaN NaN NaN NaN NaN
2  NaN NaN NaN NaN NaN
3  NaN NaN NaN NaN NaN
4  NaN NaN NaN NaN NaN
5  NaN NaN NaN NaN NaN
6  NaN NaN NaN NaN NaN
7  NaN NaN NaN NaN NaN
8  NaN NaN NaN NaN NaN
9  NaN NaN NaN NaN NaN
10 NaN NaN NaN NaN NaN
11 NaN NaN NaN NaN NaN
12 NaN NaN NaN NaN NaN
13 NaN NaN NaN NaN NaN
14 NaN NaN NaN NaN NaN
15 NaN NaN NaN NaN NaN
16 NaN NaN NaN NaN NaN
17 NaN NaN NaN NaN NaN
18 NaN NaN NaN NaN NaN
19 NaN NaN NaN NaN NaN
20 NaN NaN NaN NaN NaN
21 NaN NaN NaN NaN NaN
22 NaN NaN NaN NaN NaN
23 NaN NaN NaN NaN NaN
24 NaN NaN NaN NaN NaN
25 NaN NaN NaN NaN NaN
26 NaN NaN NaN NaN NaN
27 NaN NaN NaN NaN NaN
28 NaN NaN NaN NaN NaN
29 NaN NaN NaN NaN NaN
..  ..  ..  ..  ..  ..
70 NaN NaN NaN NaN NaN
71 NaN NaN NaN NaN NaN
72 NaN NaN NaN NaN NaN
73 NaN NaN NaN NaN NaN
74 NaN NaN NaN NaN NaN
75 NaN NaN NaN NaN NaN
76 NaN NaN NaN NaN NaN
77 NaN NaN NaN NaN NaN
78 NaN NaN NaN NaN NaN
79 NaN NaN NaN NaN NaN
80 NaN NaN NaN NaN NaN
81 NaN NaN NaN NaN NaN
82 NaN NaN NaN NaN NaN
83 NaN NaN NaN NaN NaN
84 NaN NaN NaN NaN NaN
85 NaN NaN NaN NaN NaN
86 NaN NaN NaN NaN NaN
87 NaN NaN NaN NaN NaN
88 NaN NaN NaN NaN NaN
89 NaN NaN NaN NaN NaN
90 NaN NaN NaN NaN NaN
91 NaN NaN NaN NaN NaN
92 NaN NaN NaN NaN NaN
93 NaN NaN NaN NaN NaN
94 NaN NaN NaN NaN NaN
95 NaN NaN NaN NaN NaN
96 NaN NaN NaN NaN NaN
97 NaN NaN NaN NaN NaN
98 NaN NaN NaN NaN NaN
99 NaN NaN NaN NaN NaN

[100 rows x 5 columns]